name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Save Docker Images
        run: docker pull --platform amd64 registry.k8s.io/build-image/go-runner:v2.3.1-go1.17.2-bullseye.0 ;docker save -o go-runner-v2.3.1-amd64.tar.gz registry.k8s.io/build-image/go-runner:v2.3.1-go1.17.2-bullseye.0
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: go-runner-v2.3.1-amd64.tar.gz
          tag_name: go-runner-v2.3.1-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
