name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Save Docker Images
        run: docker pull --platform amd64 registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.15.0 ;docker save -o kube-state-metrics-v2.15.0-amd64.tar.gz registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.15.0
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: kube-state-metrics-v2.15.0-amd64.tar.gz
          tag_name: kube-state-metrics-v2.15.0-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
