name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Save Docker Images
        run: docker pull --platform amd64 k8s.gcr.io/coredns:1.7.0 ;docker pull --platform amd64 k8s.gcr.io/etcd:3.4.13-0 ;docker pull --platform amd64 k8s.gcr.io/pause:3.2 ;docker pull --platform amd64 k8s.gcr.io/kube-apiserver:v1.20.0 ;docker pull --platform amd64 k8s.gcr.io/kube-scheduler:v1.20.0 ;docker pull --platform amd64 k8s.gcr.io/kube-controller-manager:v1.20.0 ;docker pull --platform amd64 k8s.gcr.io/kube-proxy:v1.20.0 ;docker save -o k8s-images-1.20.0-amd64.tar.gz k8s.gcr.io/coredns:1.7.0 k8s.gcr.io/etcd:3.4.13-0 k8s.gcr.io/pause:3.2 k8s.gcr.io/kube-apiserver:v1.20.0 k8s.gcr.io/kube-scheduler:v1.20.0 k8s.gcr.io/kube-controller-manager:v1.20.0 k8s.gcr.io/kube-proxy:v1.20.0
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: k8s-images-1.20.0-amd64.tar.gz
          tag_name: k8s-1.20.0-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
